package information_management_practice;

import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.RowSorter;
import javax.swing.SortOrder;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author RavenCosning
 */
public class GUI extends javax.swing.JFrame {

    private final StudentDAO studentDAO = new StudentDAO();
    private final CollegeDAO collegeDAO = new CollegeDAO();
    private final ProgramDAO programDAO = new ProgramDAO();
    private final DefaultTableModel studentTableModel;
    private final DefaultTableModel collegeTableModel;
    private final DefaultTableModel programTableModel;

    private int studentTotalCount = 0;
    private int studentCurrentPage = 1;
    private int studentRowsPerPage = 20;
    private boolean isSearchMode = false;
    private boolean isSorting = false;

    private boolean isCollegeSearchMode = false;
    private boolean isProgramSearchMode = false;

    public GUI() {
        initComponents();
        lockTable(tblStudents);
        lockTable(tblColleges);
        lockTable(tblPrograms);

        this.setSize(1450, 800);

        this.setLocationRelativeTo(null);

        this.setResizable(false);

        studentTableModel = (DefaultTableModel) tblStudents.getModel();
        collegeTableModel = (DefaultTableModel) tblColleges.getModel();
        programTableModel = (DefaultTableModel) tblPrograms.getModel();

        javax.swing.table.DefaultTableCellRenderer centerRenderer = new javax.swing.table.DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);

        for (int i = 0; i < tblStudents.getColumnCount(); i++) {
            tblStudents.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        for (int i = 0; i < tblColleges.getColumnCount(); i++) {
            tblColleges.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        for (int i = 0; i < tblPrograms.getColumnCount(); i++) {
            tblPrograms.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        loadCollegeTable();
        loadProgramTable();
        loadProgramCollegeCombo();
        loadStudentProgramCombo();
        loadStudentTable();

        tblStudents.getRowSorter().addRowSorterListener(e -> {
            if (isSearchMode || isSorting) {
                return;
            }

            List<? extends RowSorter.SortKey> sortKeys = tblStudents.getRowSorter().getSortKeys();
            if (sortKeys.isEmpty()) {
                return;
            }

            RowSorter.SortKey key = sortKeys.get(0);
            int col = key.getColumn();
            boolean ascending = key.getSortOrder() == SortOrder.ASCENDING;

            String[] colNames = {"id", "firstname", "lastname", "course", "year", "gender"};
            if (col < 0 || col >= colNames.length) {
                return;
            }

            isSorting = true;
            studentCurrentPage = 1;
            loadStudentTable(colNames[col], ascending);
            isSorting = false;
        });

        txtProgramCode.setToolTipText("Program Code: 2-10 uppercase letters or numbers (e.g., BSCS or BSIT2)");
        txtStudentID.setToolTipText("Format: YYYY-NNNN");
        txtCollegeCode.setToolTipText("College Code: 2-5 letters(e.g.,CCS)");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        tabMain = new javax.swing.JTabbedPane();
        Colleges = new javax.swing.JPanel();
        pnlCollegeInformation = new javax.swing.JPanel();
        lblCollegeCode = new javax.swing.JLabel();
        lblCollegeName = new javax.swing.JLabel();
        txtCollegeName = new javax.swing.JTextField();
        txtCollegeCode = new javax.swing.JTextField();
        scrColleges = new javax.swing.JScrollPane();
        tblColleges = new javax.swing.JTable();
        pnlCollegeButtons = new javax.swing.JPanel();
        btnSearchCollege = new javax.swing.JButton();
        btnAddCollege = new javax.swing.JButton();
        btnUpdateCollege = new javax.swing.JButton();
        btnDeleteCollege = new javax.swing.JButton();
        btnClearCollege = new javax.swing.JButton();
        lblCollegeCount = new javax.swing.JLabel();
        Programs = new javax.swing.JPanel();
        pnlProgramInformation = new javax.swing.JPanel();
        lblProgramCOde = new javax.swing.JLabel();
        lblCollegeName2 = new javax.swing.JLabel();
        txtProgramName = new javax.swing.JTextField();
        txtProgramCode = new javax.swing.JTextField();
        lblCollege = new javax.swing.JLabel();
        cmbProgramCollege = new javax.swing.JComboBox<>();
        srcProgam = new javax.swing.JScrollPane();
        tblPrograms = new javax.swing.JTable();
        pnlProgramButtons = new javax.swing.JPanel();
        lblProgramCount = new javax.swing.JLabel();
        btnAddProgram = new javax.swing.JButton();
        btnUpdateProgram = new javax.swing.JButton();
        btnDeleteProgram = new javax.swing.JButton();
        btnClearProgram = new javax.swing.JButton();
        btnSearchProgram = new javax.swing.JButton();
        Students = new javax.swing.JPanel();
        pnlStudentInformation = new javax.swing.JPanel();
        lblStudentID = new javax.swing.JLabel();
        txtStudentID = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblProgram = new javax.swing.JLabel();
        cmbProgram = new javax.swing.JComboBox<>();
        lblYearLevel = new javax.swing.JLabel();
        cmbYearLevel = new javax.swing.JComboBox<>();
        lblGender = new javax.swing.JLabel();
        cmbGender = new javax.swing.JComboBox<>();
        scrStudents = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();
        pnlStudentButtons = new javax.swing.JPanel();
        btnSearchStudent = new javax.swing.JButton();
        btnAddStudent = new javax.swing.JButton();
        btnUpdateStudent = new javax.swing.JButton();
        btnDeleteStudent = new javax.swing.JButton();
        btnClearStudent = new javax.swing.JButton();
        lblStudentCount = new javax.swing.JLabel();
        pnlStudentPagination = new javax.swing.JPanel();
        lblRows = new javax.swing.JLabel();
        cmbStudentRows = new javax.swing.JComboBox<>();
        btnStudentPrev = new javax.swing.JButton();
        lblStudentPage = new javax.swing.JLabel();
        btnStudentNext = new javax.swing.JButton();
        pnlHeader = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tabMain.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tabMain.setName("1"); // NOI18N

        Colleges.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        pnlCollegeInformation.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "College Information", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        lblCollegeCode.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblCollegeCode.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCollegeCode.setText("College Code");

        lblCollegeName.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblCollegeName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCollegeName.setText("College Name");

        txtCollegeName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCollegeName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCollegeName.setMinimumSize(new java.awt.Dimension(50, 25));
        txtCollegeName.setPreferredSize(new java.awt.Dimension(100, 20));
        txtCollegeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCollegeNameActionPerformed(evt);
            }
        });

        txtCollegeCode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCollegeCode.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCollegeCode.setMinimumSize(new java.awt.Dimension(50, 25));
        txtCollegeCode.setPreferredSize(new java.awt.Dimension(100, 20));
        txtCollegeCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCollegeCodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCollegeInformationLayout = new javax.swing.GroupLayout(pnlCollegeInformation);
        pnlCollegeInformation.setLayout(pnlCollegeInformationLayout);
        pnlCollegeInformationLayout.setHorizontalGroup(
            pnlCollegeInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCollegeInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCollegeInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCollegeInformationLayout.createSequentialGroup()
                        .addComponent(lblCollegeName, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCollegeName, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCollegeInformationLayout.createSequentialGroup()
                        .addComponent(lblCollegeCode, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCollegeCode, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlCollegeInformationLayout.setVerticalGroup(
            pnlCollegeInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCollegeInformationLayout.createSequentialGroup()
                .addGroup(pnlCollegeInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCollegeCode, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCollegeCode, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCollegeInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCollegeName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCollegeName, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        scrColleges.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "College Records", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12))); // NOI18N

        tblColleges.setAutoCreateRowSorter(true);
        tblColleges.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "College Code", "College Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblColleges.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblColleges.setDropMode(javax.swing.DropMode.ON);
        tblColleges.setPreferredSize(new java.awt.Dimension(1093, 561));
        tblColleges.setShowGrid(true);
        tblColleges.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCollegesMouseClicked(evt);
            }
        });
        scrColleges.setViewportView(tblColleges);

        pnlCollegeButtons.setLayout(new java.awt.GridLayout(1, 5, 100, 5));

        btnSearchCollege.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnSearchCollege.setText("Search");
        btnSearchCollege.setMaximumSize(new java.awt.Dimension(60, 35));
        btnSearchCollege.setPreferredSize(new java.awt.Dimension(60, 35));
        btnSearchCollege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCollegeActionPerformed(evt);
            }
        });

        btnAddCollege.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAddCollege.setText("Add");
        btnAddCollege.setMaximumSize(new java.awt.Dimension(60, 35));
        btnAddCollege.setPreferredSize(new java.awt.Dimension(60, 35));
        btnAddCollege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCollegeActionPerformed(evt);
            }
        });

        btnUpdateCollege.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnUpdateCollege.setText("Update");
        btnUpdateCollege.setMaximumSize(new java.awt.Dimension(60, 35));
        btnUpdateCollege.setPreferredSize(new java.awt.Dimension(60, 35));
        btnUpdateCollege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCollegeActionPerformed(evt);
            }
        });

        btnDeleteCollege.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnDeleteCollege.setText("Delete");
        btnDeleteCollege.setMaximumSize(new java.awt.Dimension(60, 35));
        btnDeleteCollege.setPreferredSize(new java.awt.Dimension(60, 35));
        btnDeleteCollege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCollegeActionPerformed(evt);
            }
        });

        btnClearCollege.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnClearCollege.setText("Clear");
        btnClearCollege.setMaximumSize(new java.awt.Dimension(60, 35));
        btnClearCollege.setPreferredSize(new java.awt.Dimension(60, 35));
        btnClearCollege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearCollegeActionPerformed(evt);
            }
        });

        lblCollegeCount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCollegeCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCollegeCount.setText("Total Colleges: 0");
        lblCollegeCount.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblCollegeCount.setMaximumSize(new java.awt.Dimension(119, 34));
        lblCollegeCount.setMinimumSize(new java.awt.Dimension(119, 34));
        lblCollegeCount.setPreferredSize(new java.awt.Dimension(119, 34));

        javax.swing.GroupLayout CollegesLayout = new javax.swing.GroupLayout(Colleges);
        Colleges.setLayout(CollegesLayout);
        CollegesLayout.setHorizontalGroup(
            CollegesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CollegesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CollegesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CollegesLayout.createSequentialGroup()
                        .addComponent(btnAddCollege, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateCollege, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteCollege, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClearCollege, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearchCollege, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlCollegeInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(CollegesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrColleges, javax.swing.GroupLayout.PREFERRED_SIZE, 1004, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCollegeCount, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1104, 1104, 1104)
                .addComponent(pnlCollegeButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(4021, Short.MAX_VALUE))
        );
        CollegesLayout.setVerticalGroup(
            CollegesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CollegesLayout.createSequentialGroup()
                .addGap(496, 496, 496)
                .addComponent(pnlCollegeButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(681, 681, 681))
            .addGroup(CollegesLayout.createSequentialGroup()
                .addGroup(CollegesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrColleges, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                    .addComponent(pnlCollegeInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CollegesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClearCollege, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteCollege, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateCollege, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchCollege, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCollegeCount, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddCollege, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(680, 680, 680))
        );

        tabMain.addTab("Colleges", Colleges);

        Programs.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        pnlProgramInformation.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Program Information", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        lblProgramCOde.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblProgramCOde.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblProgramCOde.setText("Program Code");

        lblCollegeName2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblCollegeName2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCollegeName2.setText("Program Name");

        txtProgramName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtProgramName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtProgramName.setMinimumSize(new java.awt.Dimension(50, 25));
        txtProgramName.setPreferredSize(new java.awt.Dimension(100, 20));
        txtProgramName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProgramNameActionPerformed(evt);
            }
        });

        txtProgramCode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtProgramCode.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtProgramCode.setMinimumSize(new java.awt.Dimension(50, 25));
        txtProgramCode.setPreferredSize(new java.awt.Dimension(100, 20));
        txtProgramCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProgramCodeActionPerformed(evt);
            }
        });

        lblCollege.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblCollege.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCollege.setText("College Code");

        cmbProgramCollege.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnlProgramInformationLayout = new javax.swing.GroupLayout(pnlProgramInformation);
        pnlProgramInformation.setLayout(pnlProgramInformationLayout);
        pnlProgramInformationLayout.setHorizontalGroup(
            pnlProgramInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProgramInformationLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlProgramInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlProgramInformationLayout.createSequentialGroup()
                        .addComponent(lblCollegeName2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProgramName, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlProgramInformationLayout.createSequentialGroup()
                        .addComponent(lblProgramCOde, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProgramCode, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlProgramInformationLayout.createSequentialGroup()
                        .addComponent(lblCollege, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbProgramCollege, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlProgramInformationLayout.setVerticalGroup(
            pnlProgramInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProgramInformationLayout.createSequentialGroup()
                .addGroup(pnlProgramInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProgramCOde, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProgramCode, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlProgramInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCollegeName2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProgramName, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlProgramInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCollege, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(cmbProgramCollege))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        srcProgam.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Program Records", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12))); // NOI18N

        tblPrograms.setAutoCreateRowSorter(true);
        tblPrograms.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Program Code", "Program Name", "College Code"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPrograms.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblPrograms.setDropMode(javax.swing.DropMode.ON);
        tblPrograms.setPreferredSize(new java.awt.Dimension(1093, 561));
        tblPrograms.setShowGrid(true);
        tblPrograms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProgramsMouseClicked(evt);
            }
        });
        srcProgam.setViewportView(tblPrograms);

        pnlProgramButtons.setLayout(new java.awt.GridLayout(1, 5, 100, 5));

        lblProgramCount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblProgramCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProgramCount.setText("Total Programs: 0");
        lblProgramCount.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblProgramCount.setMaximumSize(new java.awt.Dimension(160, 34));
        lblProgramCount.setMinimumSize(new java.awt.Dimension(160, 34));
        lblProgramCount.setPreferredSize(new java.awt.Dimension(160, 34));

        btnAddProgram.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAddProgram.setText("Add");
        btnAddProgram.setMaximumSize(new java.awt.Dimension(60, 35));
        btnAddProgram.setPreferredSize(new java.awt.Dimension(60, 35));
        btnAddProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProgramActionPerformed(evt);
            }
        });

        btnUpdateProgram.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnUpdateProgram.setText("Update");
        btnUpdateProgram.setMaximumSize(new java.awt.Dimension(60, 35));
        btnUpdateProgram.setPreferredSize(new java.awt.Dimension(60, 35));
        btnUpdateProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateProgramActionPerformed(evt);
            }
        });

        btnDeleteProgram.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnDeleteProgram.setText("Delete");
        btnDeleteProgram.setMaximumSize(new java.awt.Dimension(60, 35));
        btnDeleteProgram.setPreferredSize(new java.awt.Dimension(60, 35));
        btnDeleteProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteProgramActionPerformed(evt);
            }
        });

        btnClearProgram.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnClearProgram.setText("Clear");
        btnClearProgram.setMaximumSize(new java.awt.Dimension(60, 35));
        btnClearProgram.setPreferredSize(new java.awt.Dimension(60, 35));
        btnClearProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearProgramActionPerformed(evt);
            }
        });

        btnSearchProgram.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnSearchProgram.setText("Search");
        btnSearchProgram.setMaximumSize(new java.awt.Dimension(60, 35));
        btnSearchProgram.setPreferredSize(new java.awt.Dimension(60, 35));
        btnSearchProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchProgramActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProgramsLayout = new javax.swing.GroupLayout(Programs);
        Programs.setLayout(ProgramsLayout);
        ProgramsLayout.setHorizontalGroup(
            ProgramsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProgramsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProgramsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ProgramsLayout.createSequentialGroup()
                        .addComponent(btnAddProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnUpdateProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClearProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearchProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblProgramCount, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProgramsLayout.createSequentialGroup()
                        .addComponent(pnlProgramInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(srcProgam, javax.swing.GroupLayout.PREFERRED_SIZE, 999, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(96, 96, 96)
                .addComponent(pnlProgramButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(5029, Short.MAX_VALUE))
        );
        ProgramsLayout.setVerticalGroup(
            ProgramsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProgramsLayout.createSequentialGroup()
                .addGap(496, 496, 496)
                .addComponent(pnlProgramButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(681, 681, 681))
            .addGroup(ProgramsLayout.createSequentialGroup()
                .addGroup(ProgramsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(srcProgam, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                    .addComponent(pnlProgramInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProgramsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClearProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProgramCount, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(btnAddProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(679, Short.MAX_VALUE))
        );

        tabMain.addTab("Programs", Programs);

        Students.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        pnlStudentInformation.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Student Information", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        pnlStudentInformation.setLayout(new java.awt.GridLayout(6, 2, 5, 5));

        lblStudentID.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblStudentID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblStudentID.setText("Student ID (YYYY-NNNN):");
        pnlStudentInformation.add(lblStudentID);

        txtStudentID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtStudentID.setMinimumSize(new java.awt.Dimension(50, 25));
        txtStudentID.setPreferredSize(new java.awt.Dimension(100, 20));
        pnlStudentInformation.add(txtStudentID);

        lblFirstName.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblFirstName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFirstName.setText("First Name:");
        pnlStudentInformation.add(lblFirstName);

        txtFirstName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFirstName.setMinimumSize(new java.awt.Dimension(50, 25));
        txtFirstName.setPreferredSize(new java.awt.Dimension(100, 20));
        pnlStudentInformation.add(txtFirstName);

        lblLastName.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblLastName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLastName.setText("Last Name:");
        pnlStudentInformation.add(lblLastName);

        txtLastName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLastName.setMinimumSize(new java.awt.Dimension(50, 25));
        txtLastName.setPreferredSize(new java.awt.Dimension(100, 20));
        pnlStudentInformation.add(txtLastName);

        lblProgram.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblProgram.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblProgram.setText("Program:");
        lblProgram.setToolTipText("");
        lblProgram.setFocusable(false);
        pnlStudentInformation.add(lblProgram);

        cmbProgram.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbProgram.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BSCS", "BSIT", "BSCA", "BSIS" }));
        cmbProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProgramActionPerformed(evt);
            }
        });
        pnlStudentInformation.add(cmbProgram);

        lblYearLevel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblYearLevel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblYearLevel.setText("Year Level:");
        pnlStudentInformation.add(lblYearLevel);

        cmbYearLevel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbYearLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "1", "2", "3", "4", "5" }));
        cmbYearLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbYearLevelActionPerformed(evt);
            }
        });
        pnlStudentInformation.add(cmbYearLevel);

        lblGender.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblGender.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGender.setText("Gender:");
        lblGender.setPreferredSize(new java.awt.Dimension(580, 20));
        pnlStudentInformation.add(lblGender);

        cmbGender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Male", "Female", "Other" }));
        pnlStudentInformation.add(cmbGender);

        scrStudents.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Student Records", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12))); // NOI18N

        tblStudents.setAutoCreateRowSorter(true);
        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Program", "Year", "Gender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblStudents.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblStudents.setDropMode(javax.swing.DropMode.ON);
        tblStudents.setPreferredSize(new java.awt.Dimension(1093, 561));
        tblStudents.setShowGrid(true);
        tblStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStudentsMouseClicked(evt);
            }
        });
        scrStudents.setViewportView(tblStudents);
        tblStudents.getAccessibleContext().setAccessibleName("");

        pnlStudentButtons.setLayout(new java.awt.GridLayout(1, 5, 100, 5));

        btnSearchStudent.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnSearchStudent.setText("Search");
        btnSearchStudent.setMaximumSize(new java.awt.Dimension(60, 35));
        btnSearchStudent.setPreferredSize(new java.awt.Dimension(60, 35));
        btnSearchStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchStudentActionPerformed(evt);
            }
        });

        btnAddStudent.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAddStudent.setText("Add");
        btnAddStudent.setMaximumSize(new java.awt.Dimension(60, 35));
        btnAddStudent.setPreferredSize(new java.awt.Dimension(60, 35));
        btnAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudentActionPerformed(evt);
            }
        });

        btnUpdateStudent.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnUpdateStudent.setText("Update");
        btnUpdateStudent.setMaximumSize(new java.awt.Dimension(60, 35));
        btnUpdateStudent.setPreferredSize(new java.awt.Dimension(60, 35));
        btnUpdateStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStudentActionPerformed(evt);
            }
        });

        btnDeleteStudent.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnDeleteStudent.setText("Delete");
        btnDeleteStudent.setMaximumSize(new java.awt.Dimension(60, 35));
        btnDeleteStudent.setPreferredSize(new java.awt.Dimension(60, 35));
        btnDeleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteStudentActionPerformed(evt);
            }
        });

        btnClearStudent.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnClearStudent.setText("Clear");
        btnClearStudent.setMaximumSize(new java.awt.Dimension(60, 35));
        btnClearStudent.setPreferredSize(new java.awt.Dimension(60, 35));
        btnClearStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearStudentActionPerformed(evt);
            }
        });

        lblStudentCount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStudentCount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStudentCount.setText("Total Students: 0");
        lblStudentCount.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pnlStudentPagination.setBorder(new javax.swing.border.MatteBorder(null));

        lblRows.setText("Rows:");
        lblRows.setMaximumSize(new java.awt.Dimension(45, 25));
        lblRows.setMinimumSize(new java.awt.Dimension(45, 25));
        lblRows.setPreferredSize(new java.awt.Dimension(45, 25));

        cmbStudentRows.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "20", "50", "100" }));
        cmbStudentRows.setMinimumSize(new java.awt.Dimension(70, 30));
        cmbStudentRows.setPreferredSize(new java.awt.Dimension(70, 30));
        cmbStudentRows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStudentRowsActionPerformed(evt);
            }
        });

        btnStudentPrev.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnStudentPrev.setText("< Prev");
        btnStudentPrev.setMaximumSize(new java.awt.Dimension(90, 30));
        btnStudentPrev.setMinimumSize(new java.awt.Dimension(90, 30));
        btnStudentPrev.setPreferredSize(new java.awt.Dimension(90, 30));
        btnStudentPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentPrevActionPerformed(evt);
            }
        });

        lblStudentPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStudentPage.setText("Page 1 of 1");
        lblStudentPage.setToolTipText("");
        lblStudentPage.setMaximumSize(new java.awt.Dimension(100, 25));
        lblStudentPage.setMinimumSize(new java.awt.Dimension(100, 25));
        lblStudentPage.setPreferredSize(new java.awt.Dimension(100, 25));

        btnStudentNext.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnStudentNext.setText("Next >");
        btnStudentNext.setMaximumSize(new java.awt.Dimension(90, 30));
        btnStudentNext.setMinimumSize(new java.awt.Dimension(90, 30));
        btnStudentNext.setPreferredSize(new java.awt.Dimension(90, 30));
        btnStudentNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlStudentPaginationLayout = new javax.swing.GroupLayout(pnlStudentPagination);
        pnlStudentPagination.setLayout(pnlStudentPaginationLayout);
        pnlStudentPaginationLayout.setHorizontalGroup(
            pnlStudentPaginationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStudentPaginationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRows, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbStudentRows, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnStudentPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStudentPage, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnStudentNext, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlStudentPaginationLayout.setVerticalGroup(
            pnlStudentPaginationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStudentPaginationLayout.createSequentialGroup()
                .addGroup(pnlStudentPaginationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlStudentPaginationLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlStudentPaginationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbStudentRows, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblRows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlStudentPaginationLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(pnlStudentPaginationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnStudentPrev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblStudentPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnStudentNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout StudentsLayout = new javax.swing.GroupLayout(Students);
        Students.setLayout(StudentsLayout);
        StudentsLayout.setHorizontalGroup(
            StudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentsLayout.createSequentialGroup()
                        .addComponent(pnlStudentInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 1007, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StudentsLayout.createSequentialGroup()
                        .addComponent(btnAddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClearStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearchStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(280, 280, 280)
                        .addComponent(pnlStudentPagination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(190, 190, 190)
                        .addComponent(lblStudentCount)))
                .addGap(12, 12, 12)
                .addComponent(pnlStudentButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(5112, Short.MAX_VALUE))
        );
        StudentsLayout.setVerticalGroup(
            StudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentsLayout.createSequentialGroup()
                .addGroup(StudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblStudentCount, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(StudentsLayout.createSequentialGroup()
                        .addGroup(StudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(StudentsLayout.createSequentialGroup()
                                .addGap(508, 508, 508)
                                .addComponent(pnlStudentButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pnlStudentInformation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scrStudents, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(StudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlStudentPagination, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(StudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnAddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnUpdateStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnDeleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnClearStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSearchStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 681, Short.MAX_VALUE))
        );

        tabMain.addTab("Students", Students);

        pnlHeader.setMaximumSize(new java.awt.Dimension(1450, 88));
        pnlHeader.setPreferredSize(new java.awt.Dimension(1450, 88));

        lblHeader.setForeground(new java.awt.Color(255, 51, 51));
        lblHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/information_management_practice/IIT_Header.png"))); // NOI18N

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 1910, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tabMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tabMain, javax.swing.GroupLayout.PREFERRED_SIZE, 1344, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tabMain.getAccessibleContext().setAccessibleName("1");

        pack();
    }// </editor-fold>                        

    private void btnClearStudentActionPerformed(java.awt.event.ActionEvent evt) {                                                
        txtStudentID.setText("");
        txtFirstName.setText("");
        txtLastName.setText("");

        if (cmbProgram.getItemCount() > 0) {
            cmbProgram.setSelectedIndex(0);
        }
        if (cmbYearLevel.getItemCount() > 0) {
            cmbYearLevel.setSelectedIndex(0);
        }
        if (cmbGender.getItemCount() > 0) {
            cmbGender.setSelectedIndex(0);
        }

        tblStudents.clearSelection();
        txtStudentID.requestFocus();

        // Restore paginated view after search
        studentCurrentPage = 1;
        loadStudentTable();
        isSearchMode = false;
    }                                               

    private void btnDeleteStudentActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        int viewRow = tblStudents.getSelectedRow();
        if (viewRow == -1) {
            warn("Please select a student record first.", "No Record Selected");
            return;
        }
        int modelRow = tblStudents.convertRowIndexToModel(viewRow);
        String id = studentTableModel.getValueAt(modelRow, 0).toString().trim();
        String name = studentTableModel.getValueAt(modelRow, 1).toString().trim()
                + " " + studentTableModel.getValueAt(modelRow, 2).toString().trim();
        if (!confirm("Delete student " + id + " — " + name + "?\nThis action cannot be undone.", "Confirm Delete")) {
            return;
        }
        boolean success = studentDAO.deleteStudent(id);
        if (!success) {
            error("Failed to delete student.\nPlease try again.", "Database Error");
            return;
        }
        info("Student \"" + name + "\" deleted successfully.", "Success");
        loadStudentTable();
        btnClearStudent.doClick();
    }                                                

    private void btnUpdateStudentActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        int viewRow = tblStudents.getSelectedRow();
        if (viewRow == -1) {
            warn("Please select a student record first.", "No Record Selected");
            return;
        }
        int modelRow = tblStudents.convertRowIndexToModel(viewRow);
        String originalId = studentTableModel.getValueAt(modelRow, 0).toString().trim();
        String id = txtStudentID.getText().trim();
        String firstName = toTitleCase(txtFirstName.getText().trim());
        String lastName = toTitleCase(txtLastName.getText().trim());
        Object progObj = cmbProgram.getSelectedItem();
        if (progObj == null) {
            warn("No programs available.", "Program Required");
            return;
        }
        String program = progObj.toString().trim();
        String yearLevel = cmbYearLevel.getSelectedItem().toString();
        String gender = cmbGender.getSelectedItem().toString();
        if (program.equalsIgnoreCase("All") || yearLevel.equalsIgnoreCase("All") || gender.equalsIgnoreCase("All")) {
            error("Please select a valid Program, Year Level, and Gender (not 'All').", "Invalid Selection");
            return;
        }
        if (id.isEmpty() || firstName.isEmpty() || lastName.isEmpty()) {
            warn("Please fill in all required fields.", "Missing Information");
            return;
        }
        if (!id.matches("\\d{4}-\\d{4}")) {
            error("Invalid Student ID format.\nRequired: YYYY-NNNN.", "Invalid Format");
            return;
        }
        int year = Integer.parseInt(id.substring(0, 4));
        int currentYear = java.time.Year.now().getValue();
        if (year < 2015 || year > currentYear) {
            error("Student year must be between 2015 and " + currentYear + ".", "Invalid Year");
            return;
        }
        if (!firstName.matches("[a-zA-Z\\-' ]+")) {
            error("First name contains invalid characters.", "Invalid Format");
            return;
        }
        if (!lastName.matches("[a-zA-Z\\-' ]+")) {
            error("Last name contains invalid characters.", "Invalid Format");
            return;
        }
        if (!originalId.equalsIgnoreCase(id) && studentDAO.exists(id)) {
            warn("Student ID \"" + id + "\" already exists.", "Duplicate ID");
            return;
        }
        if (!confirm("Save changes to Student ID " + originalId + "?", "Confirm Update")) {
            return;
        }
        boolean success = studentDAO.updateStudent(originalId, new Student(id, firstName, lastName, program, Integer.parseInt(yearLevel), gender));
        if (!success) {
            error("Failed to update student.", "Database Error");
            return;
        }
        info("Student updated successfully.", "Success");
        loadStudentTable();
        btnClearStudent.doClick();
        selectRowByCode(tblStudents, studentTableModel, id, 0);
    }                                                

    private void btnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {                                              
        String id = txtStudentID.getText().trim();
        String firstName = toTitleCase(txtFirstName.getText().trim());
        String lastName = toTitleCase(txtLastName.getText().trim());
        Object progObj = cmbProgram.getSelectedItem();
        if (progObj == null) {
            warn("No programs available.", "Program Required");
            return;
        }
        String program = progObj.toString().trim();
        String yearLevel = cmbYearLevel.getSelectedItem().toString();
        String gender = cmbGender.getSelectedItem().toString();
        if (program.equalsIgnoreCase("All") || yearLevel.equalsIgnoreCase("All") || gender.equalsIgnoreCase("All")) {
            error("Please select a valid Program, Year Level, and Gender (not 'All').", "Invalid Selection");
            return;
        }
        if (id.isEmpty() || firstName.isEmpty() || lastName.isEmpty()) {
            warn("Please fill in all required fields.", "Missing Information");
            return;
        }
        if (!id.matches("\\d{4}-\\d{4}")) {
            error("Invalid Student ID format.\nRequired: YYYY-NNNN.", "Invalid Format");
            return;
        }
        int year = Integer.parseInt(id.substring(0, 4));
        int currentYear = java.time.Year.now().getValue();
        if (year < 2015 || year > currentYear) {
            error("Student year must be between 2015 and " + currentYear + ".", "Invalid Year");
            return;
        }
        if (!firstName.matches("[a-zA-Z\\-' ]+")) {
            error("First name contains invalid characters.", "Invalid Format");
            return;
        }
        if (!lastName.matches("[a-zA-Z\\-' ]+")) {
            error("Last name contains invalid characters.", "Invalid Format");
            return;
        }
        if (studentDAO.exists(id)) {
            warn("Student ID \"" + id + "\" already exists.", "Duplicate ID");
            return;
        }
        boolean success = studentDAO.addStudent(new Student(id, firstName, lastName, program, Integer.parseInt(yearLevel), gender));
        if (!success) {
            error("Failed to add student.\nPlease try again.", "Database Error");
            return;
        }
        info("Student \"" + firstName + " " + lastName + "\" added successfully.", "Success");
        loadStudentTable();
        btnClearStudent.doClick();
        selectRowByCode(tblStudents, studentTableModel, id, 0);
    }                                             

    private void btnSearchStudentActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        String studentId = txtStudentID.getText().trim();
        String firstName = txtFirstName.getText().trim();
        String lastName = txtLastName.getText().trim();
        String programCode = (cmbProgram.getSelectedItem() == null)
                ? "" : cmbProgram.getSelectedItem().toString().trim();
        String yearLevel = (cmbYearLevel.getSelectedItem() == null)
                ? "" : cmbYearLevel.getSelectedItem().toString().trim();
        String gender = (cmbGender.getSelectedItem() == null)
                ? "" : cmbGender.getSelectedItem().toString().trim();

        if (programCode.equalsIgnoreCase("all")) {
            programCode = "";
        }
        if (yearLevel.equalsIgnoreCase("all")) {
            yearLevel = "";
        }
        if (gender.equalsIgnoreCase("all")) {
            gender = "";
        }

        boolean hasSearchInput = !studentId.isEmpty() || !firstName.isEmpty()
                || !lastName.isEmpty() || !programCode.isEmpty()
                || !yearLevel.isEmpty() || !gender.isEmpty();

        if (!hasSearchInput) {
            warn("Enter at least one search criterion.", "No Search Criteria");
            return;
        }

        List<Student> results = studentDAO.searchAll(studentId, firstName, lastName,
                programCode, yearLevel, gender);

        if (results.isEmpty()) {
            info("No matching student record found.", "No Results");
            return;
        }

        // Load ALL results into table
        studentTableModel.setRowCount(0);
        for (Student s : results) {
            studentTableModel.addRow(new Object[]{
                s.getId(), s.getFirstName(), s.getLastName(),
                s.getProgramCode(), s.getYear(), s.getGender()
            });
        }

        lblStudentCount.setText("Search Results: " + results.size());
        lblStudentPage.setText("Search Mode");
        btnStudentPrev.setEnabled(false);
        btnStudentNext.setEnabled(false);
        isSearchMode = true;

    }                                                


    private void tblStudentsMouseClicked(java.awt.event.MouseEvent evt) {                                         
        int row = tblStudents.getSelectedRow();
        if (row == -1) {
            return;
        }
        int modelRow = tblStudents.convertRowIndexToModel(row);

        txtStudentID.setText(studentTableModel.getValueAt(modelRow, 0).toString());
        txtFirstName.setText(studentTableModel.getValueAt(modelRow, 1).toString());
        txtLastName.setText(studentTableModel.getValueAt(modelRow, 2).toString());

        cmbProgram.setSelectedItem(studentTableModel.getValueAt(modelRow, 3));
        cmbYearLevel.setSelectedItem(String.valueOf(studentTableModel.getValueAt(modelRow, 4)));
        cmbGender.setSelectedItem(studentTableModel.getValueAt(modelRow, 5));
    }                                        

    private void cmbYearLevelActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void cmbProgramActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void btnClearCollegeActionPerformed(java.awt.event.ActionEvent evt) {                                                
        txtCollegeCode.setText("");
        txtCollegeName.setText("");
        tblColleges.clearSelection();
        txtCollegeCode.requestFocus();
        if (isCollegeSearchMode) {
            loadCollegeTable();
            isCollegeSearchMode = false;
        }
    }                                               

    private void btnDeleteCollegeActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        int viewRow = tblColleges.getSelectedRow();
        if (viewRow == -1) {
            warn("Please select a college record first.", "No Record Selected");
            return;
        }
        int modelRow = tblColleges.convertRowIndexToModel(viewRow);
        String code = collegeTableModel.getValueAt(modelRow, 0).toString().trim().toUpperCase();
        String name = collegeTableModel.getValueAt(modelRow, 1).toString().trim();
        int programCount = programDAO.countByCollege(code);
        if (programCount > 0) {
            if (!confirm("College " + code + " has " + programCount + " program(s).\n"
                    + "Deleting it will set those programs' college to N/A.\nContinue?",
                    "Confirm Delete")) {
                return;
            }
        }
        if (!confirm("Delete college " + code + " — " + name + "?\nThis action cannot be undone.", "Confirm Delete")) {
            return;
        }
        boolean success = collegeDAO.deleteCollege(code);
        if (!success) {
            error("Failed to delete college.\nPlease try again.", "Database Error");
            return;
        }
        info("College \"" + name + "\" deleted successfully.", "Success");
        loadCollegeTable();
        loadProgramTable();
        loadProgramCollegeCombo();
        btnClearCollege.doClick();
    }                                                

    private void btnUpdateCollegeActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        int viewRow = tblColleges.getSelectedRow();
        if (viewRow == -1) {
            warn("Please select a college record first.", "No Record Selected");
            return;
        }
        int modelRow = tblColleges.convertRowIndexToModel(viewRow);
        String originalCode = collegeTableModel.getValueAt(modelRow, 0).toString().trim().toUpperCase();
        String newCode = txtCollegeCode.getText().trim().toUpperCase();
        String name = txtCollegeName.getText().trim();
        if (newCode.isEmpty() || name.isEmpty()) {
            warn("Please fill in all required fields.", "Missing Information");
            return;
        }
        if (!newCode.matches("[A-Z]{2,5}")) {
            error("Invalid College Code format.\nMust be 2–5 letters (e.g., CCS).", "Invalid Format");
            return;
        }
        if (!name.matches("[a-zA-Z&\\-' ]+")) {
            error("College name contains invalid characters.", "Invalid Format");
            return;
        }
        if (!originalCode.equalsIgnoreCase(newCode) && collegeDAO.exists(newCode)) {
            error("College code \"" + newCode + "\" already exists.", "Duplicate Entry");
            return;
        }
        if (!confirm("Save changes to College Code " + originalCode + "?", "Confirm Update")) {
            return;
        }
        boolean success = collegeDAO.updateCollege(originalCode, new College(newCode, name));
        if (!success) {
            error("Failed to update college.", "Database Error");
            return;
        }
        info("College \"" + name + "\" updated successfully.", "Success");
        loadCollegeTable();
        loadProgramTable();
        loadProgramCollegeCombo();
        btnClearCollege.doClick();
        selectRowByCode(tblColleges, collegeTableModel, newCode, 0);
    }                                                

    private void btnAddCollegeActionPerformed(java.awt.event.ActionEvent evt) {                                              
        String code = txtCollegeCode.getText().trim().toUpperCase();
        String name = txtCollegeName.getText().trim();
        if (code.isEmpty() || name.isEmpty()) {
            warn("Please fill in all required fields.", "Missing Information");
            return;
        }
        if (!code.matches("[A-Z]{2,5}")) {
            error("Invalid College Code format.\nMust be 2–5 letters only (e.g., CCS).", "Invalid Format");
            return;
        }
        if (!name.matches("[a-zA-Z&\\-' ]+")) {
            error("College name contains invalid characters.", "Invalid Format");
            return;
        }
        if (collegeDAO.exists(code)) {
            error("College code \"" + code + "\" already exists.", "Duplicate Entry");
            return;
        }
        boolean success = collegeDAO.addCollege(new College(code, name));
        if (!success) {
            error("Failed to add college.\nPlease try again.", "Database Error");
            return;
        }
        info("College \"" + name + "\" added successfully.", "Success");
        loadCollegeTable();
        loadProgramCollegeCombo();
        btnClearCollege.doClick();
        selectRowByCode(tblColleges, collegeTableModel, code, 0);
    }                                             

    private void btnSearchCollegeActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        String collegeCode = txtCollegeCode.getText().trim().toUpperCase();
        String collegeName = txtCollegeName.getText().trim();

        if (collegeCode.isEmpty() && collegeName.isEmpty()) {
            warn("Enter at least one search field: College Code or College Name.", "Search Required");
            return;
        }

        List<College> results = collegeDAO.searchAll(collegeCode, collegeName);

        if (results.isEmpty()) {
            info("No matching college record found.", "No Results");
            return;
        }

        collegeTableModel.setRowCount(0);
        for (College c : results) {
            collegeTableModel.addRow(new Object[]{c.getCode(), c.getName()});
        }

        lblCollegeCount.setText("Search Results: " + results.size());
        txtCollegeCode.setText("");
        txtCollegeName.setText("");
        tblColleges.clearSelection();
        isCollegeSearchMode = true;
    }                                                

    private void tblCollegesMouseClicked(java.awt.event.MouseEvent evt) {                                         
        int viewRow = tblColleges.getSelectedRow();
        if (viewRow == -1) {
            return;
        }

        int modelRow = tblColleges.convertRowIndexToModel(viewRow);

        txtCollegeCode.setText(collegeTableModel.getValueAt(modelRow, 0).toString());
        txtCollegeName.setText(collegeTableModel.getValueAt(modelRow, 1).toString());
        txtCollegeName.setCaretPosition(0);
    }                                        

    private void txtCollegeNameActionPerformed(java.awt.event.ActionEvent evt) {                                               

    }                                              

    private void btnClearProgramActionPerformed(java.awt.event.ActionEvent evt) {                                                
        txtProgramCode.setText("");
        txtProgramName.setText("");
        if (cmbProgramCollege.getItemCount() > 0) {
            cmbProgramCollege.setSelectedIndex(0);
        }
        tblPrograms.clearSelection();
        txtProgramCode.requestFocus();
        if (isProgramSearchMode) {
            loadProgramTable();
            isProgramSearchMode = false;
        }
    }                                               

    private void btnDeleteProgramActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        int viewRow = tblPrograms.getSelectedRow();
        if (viewRow == -1) {
            warn("Please select a program record first.", "No Record Selected");
            return;
        }
        int modelRow = tblPrograms.convertRowIndexToModel(viewRow);
        String code = programTableModel.getValueAt(modelRow, 0).toString().trim().toUpperCase();
        String name = programTableModel.getValueAt(modelRow, 1).toString().trim();
        int studentCount = studentDAO.countByProgram(code);
        if (studentCount > 0) {
            if (!confirm("Program " + code + " has " + studentCount + " student(s).\n"
                    + "Deleting it will set those students' program to NOT ENROLLED.\nContinue?",
                    "Confirm Delete")) {
                return;
            }
        }
        if (!confirm("Delete program " + code + " — " + name + "?\nThis action cannot be undone.", "Confirm Delete")) {
            return;
        }
        boolean success = programDAO.deleteProgram(code);
        if (!success) {
            error("Failed to delete program.\nPlease try again.", "Database Error");
            return;
        }
        info("Program \"" + name + "\" deleted successfully.", "Success");
        loadProgramTable();
        loadStudentTable();
        loadStudentProgramCombo();
        btnClearProgram.doClick();
    }                                                

    private void btnUpdateProgramActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        int viewRow = tblPrograms.getSelectedRow();
        if (viewRow == -1) {
            warn("Please select a program record first.", "No Record Selected");
            return;
        }
        int modelRow = tblPrograms.convertRowIndexToModel(viewRow);
        String originalCode = programTableModel.getValueAt(modelRow, 0).toString().trim().toUpperCase();
        String code = txtProgramCode.getText().trim().toUpperCase();
        String name = txtProgramName.getText().trim();
        Object colObj = cmbProgramCollege.getSelectedItem();
        if (colObj == null || colObj.toString().trim().isEmpty()) {
            warn("No colleges available.", "College Required");
            return;
        }
        String collegeCode = colObj.toString().trim().toUpperCase();
        if (collegeCode.equalsIgnoreCase("All")) {
            error("Please select a valid College (not 'All').", "Invalid College Selection");
            return;
        }
        if (code.isEmpty() || name.isEmpty()) {
            warn("Please fill in all required fields.", "Missing Information");
            return;
        }
        if (!code.matches("[A-Z0-9]{2,10}")) {
            error("Invalid Program Code format.\nMust be 2–10 letters/numbers.", "Invalid Format");
            return;
        }
        if (!name.matches("[a-zA-Z&\\-' ]+")) {
            error("Program name contains invalid characters.", "Invalid Format");
            return;
        }
        if (!originalCode.equalsIgnoreCase(code) && programDAO.exists(code)) {
            error("Program code \"" + code + "\" already exists.", "Duplicate Entry");
            return;
        }
        if (!confirm("Save changes to Program Code " + originalCode + "?", "Confirm Update")) {
            return;
        }
        boolean success = programDAO.updateProgram(originalCode, new Program(code, name, collegeCode));
        if (!success) {
            error("Failed to update program.", "Database Error");
            return;
        }
        info("Program \"" + name + "\" updated successfully.", "Success");
        loadProgramTable();
        loadStudentProgramCombo();
        loadStudentTable();
        btnClearProgram.doClick();
        selectRowByCode(tblPrograms, programTableModel, code, 0);
    }                                                

    private void btnAddProgramActionPerformed(java.awt.event.ActionEvent evt) {                                              
        String code = txtProgramCode.getText().trim().toUpperCase();
        String name = txtProgramName.getText().trim();
        Object colObj = cmbProgramCollege.getSelectedItem();
        if (colObj == null || colObj.toString().trim().isEmpty()) {
            warn("No colleges available.", "College Required");
            return;
        }
        String collegeCode = colObj.toString().trim().toUpperCase();
        if (collegeCode.equalsIgnoreCase("All")) {
            error("Please select a valid College (not 'All').", "Invalid College Selection");
            return;
        }
        if (code.isEmpty() || name.isEmpty()) {
            warn("Please fill in all required fields.", "Missing Information");
            return;
        }
        if (!code.matches("[A-Z0-9]{2,10}")) {
            error("Invalid Program Code format.\nMust be 2–10 letters/numbers.", "Invalid Format");
            return;
        }
        if (!name.matches("[a-zA-Z&\\-' ]+")) {
            error("Program name contains invalid characters.", "Invalid Format");
            return;
        }
        if (programDAO.exists(code)) {
            error("Program code \"" + code + "\" already exists.", "Duplicate Entry");
            return;
        }
        boolean success = programDAO.addProgram(new Program(code, name, collegeCode));
        if (!success) {
            error("Failed to add program.\nPlease try again.", "Database Error");
            return;
        }
        info("Program \"" + name + "\" added successfully.", "Success");
        loadProgramTable();
        loadStudentTable();
        loadStudentProgramCombo();
        loadStudentTable();
        btnClearProgram.doClick();
        selectRowByCode(tblPrograms, programTableModel, code, 0);
    }                                             

    private void btnSearchProgramActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        String programCode = txtProgramCode.getText().trim().toUpperCase();
        String programName = txtProgramName.getText().trim();

        String collegeCode = (cmbProgramCollege.getSelectedItem() == null)
                ? "" : cmbProgramCollege.getSelectedItem().toString().trim();

        if (collegeCode.equalsIgnoreCase("all")) {
            collegeCode = "";
        }

        boolean hasSearchInput = !programCode.isEmpty() || !programName.isEmpty() || !collegeCode.isEmpty();

        if (!hasSearchInput) {
            warn("Enter a Program Code/Name or select a College to search.", "No Search Criteria");
            return;
        }

        List<Program> results = programDAO.searchAll(programCode, programName, collegeCode);

        if (results.isEmpty()) {
            info("No matching program record found.", "No Results");
            return;
        }

        programTableModel.setRowCount(0);
        for (Program p : results) {
            programTableModel.addRow(new Object[]{p.getCode(), p.getName(), p.getCollegeCode()});
        }

        lblProgramCount.setText("Search Results: " + results.size());
        txtProgramCode.setText("");
        txtProgramName.setText("");
        if (cmbProgramCollege.getItemCount() > 0) {
            cmbProgramCollege.setSelectedIndex(0);
        }
        tblPrograms.clearSelection();
        isProgramSearchMode = true;
    }                                                

    private void tblProgramsMouseClicked(java.awt.event.MouseEvent evt) {                                         
        int row = tblPrograms.getSelectedRow();
        if (row == -1) {
            return;
        }

        int modelRow = tblPrograms.convertRowIndexToModel(row);

        txtProgramCode.setText(programTableModel.getValueAt(modelRow, 0).toString());
        txtProgramName.setText(programTableModel.getValueAt(modelRow, 1).toString());

        String colCode = programTableModel.getValueAt(modelRow, 2).toString();
        cmbProgramCollege.setSelectedItem(colCode);
    }                                        

    private void txtProgramCodeActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void txtProgramNameActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void txtCollegeCodeActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void btnStudentPrevActionPerformed(java.awt.event.ActionEvent evt) {                                               
        if (studentCurrentPage > 1) {
            studentCurrentPage--;
            loadStudentTable();
        }
    }                                              

    private void btnStudentNextActionPerformed(java.awt.event.ActionEvent evt) {                                               
        int totalPages = (int) Math.ceil((double) studentTotalCount / studentRowsPerPage);
        if (studentCurrentPage < totalPages) {
            studentCurrentPage++;
            loadStudentTable();
        }
    }                                              

    private void cmbStudentRowsActionPerformed(java.awt.event.ActionEvent evt) {                                               
        if (isSearchMode) {
            return;
        }
        studentRowsPerPage = Integer.parseInt(cmbStudentRows.getSelectedItem().toString());
        studentCurrentPage = 1;
        loadStudentTable();
    }                                              

    // ==========================================
    //          HELPER METHODS
    // ==========================================
    // Dialog Helpers
    private void info(String message, String title) {
        JOptionPane.showMessageDialog(this, message, title, JOptionPane.INFORMATION_MESSAGE);
    }

    private void warn(String message, String title) {
        JOptionPane.showMessageDialog(this, message, title, JOptionPane.WARNING_MESSAGE);
    }

    private void error(String message, String title) {
        JOptionPane.showMessageDialog(this, message, title, JOptionPane.ERROR_MESSAGE);
    }

    private boolean confirm(String message, String title) {
        return JOptionPane.showConfirmDialog(
                this,
                message,
                title,
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        ) == JOptionPane.YES_OPTION;
    }

    /**
     * Converts a string to Title Case (e.g., "HELLO world" -> "Hello World").
     */
    private String toTitleCase(String text) {
        if (text == null || text.isEmpty()) {
            return text;
        }

        StringBuilder converted = new StringBuilder();
        boolean convertNext = true;

        for (char ch : text.toCharArray()) {

            if (Character.isSpaceChar(ch) || ch == '-' || ch == '\'') {
                convertNext = true;
                converted.append(ch);
                continue;
            }
            if (convertNext) {
                converted.append(Character.toUpperCase(ch));
                convertNext = false;
            } else {
                converted.append(Character.toLowerCase(ch));
            }
        }

        return converted.toString();
    }

    //DAO HELPER
    //
    // 
    private void loadStudentTable() {
        studentTableModel.setRowCount(0);
        int offset = (studentCurrentPage - 1) * studentRowsPerPage;
        List<Student> students = studentDAO.search("", "id", true, studentRowsPerPage, offset);
        for (Student s : students) {
            studentTableModel.addRow(new Object[]{s.getId(), s.getFirstName(), s.getLastName(), s.getProgramCode(), s.getYear(), s.getGender()});
        }
        studentTotalCount = studentDAO.count("");
        lblStudentCount.setText("Total Students: " + studentTotalCount);
        updateStudentPagination(studentTotalCount);
    }

    private void updateStudentPagination(int total) {
        int totalPages = (int) Math.ceil((double) total / studentRowsPerPage);
        if (totalPages == 0) {
            totalPages = 1;
        }
        lblStudentPage.setText("Page " + studentCurrentPage + " of " + totalPages);
        btnStudentPrev.setEnabled(studentCurrentPage > 1);
        btnStudentNext.setEnabled(studentCurrentPage < totalPages);
    }

    //COLLEGE RELATED CODES
    //
    //
    private void loadCollegeTable() {
        collegeTableModel.setRowCount(0);
        List<College> colleges = collegeDAO.getAllColleges();
        for (College c : colleges) {
            collegeTableModel.addRow(new Object[]{c.getCode(), c.getName()});
        }
        lblCollegeCount.setText("Total Colleges: " + colleges.size());
    }

    //Program Codes
    //
    //
    private void loadProgramTable() {
        programTableModel.setRowCount(0);
        List<Program> programs = programDAO.getAllPrograms();
        for (Program p : programs) {
            programTableModel.addRow(new Object[]{p.getCode(), p.getName(), p.getCollegeCode()});
        }
        lblProgramCount.setText("Total Programs: " + programs.size());
    }

    private void loadProgramCollegeCombo() {
        cmbProgramCollege.removeAllItems();
        cmbProgramCollege.addItem("All");
        for (College c : collegeDAO.getAllColleges()) {
            cmbProgramCollege.addItem(c.getCode());
        }
        if (cmbProgramCollege.getItemCount() > 0) {
            cmbProgramCollege.setSelectedIndex(0);
        }
    }

    private void loadStudentProgramCombo() {
        cmbProgram.removeAllItems();
        cmbProgram.addItem("All");
        for (Program p : programDAO.getAllPrograms()) {
            cmbProgram.addItem(p.getCode());
        }
        if (cmbProgram.getItemCount() > 0) {
            cmbProgram.setSelectedIndex(0);
        }
    }

    private void selectRowByCode(JTable table, DefaultTableModel model, String value, int columnIndex) {
        for (int i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, columnIndex).toString().equalsIgnoreCase(value)) {
                int viewRow = table.convertRowIndexToView(i);
                table.setRowSelectionInterval(viewRow, viewRow);
                table.scrollRectToVisible(table.getCellRect(viewRow, 0, true));
                return;
            }
        }
    }

    private void lockTable(JTable table) {
        table.getTableHeader().setReorderingAllowed(false);
        table.getTableHeader().setResizingAllowed(false);
    }

    private void loadStudentTable(String sortBy, boolean ascending) {
        studentTableModel.setRowCount(0);
        int offset = (studentCurrentPage - 1) * studentRowsPerPage;
        List<Student> students = studentDAO.search("", sortBy, ascending, studentRowsPerPage, offset);
        for (Student s : students) {
            studentTableModel.addRow(new Object[]{
                s.getId(), s.getFirstName(), s.getLastName(),
                s.getProgramCode(), s.getYear(), s.getGender()
            });
        }
        studentTotalCount = studentDAO.count("");
        lblStudentCount.setText("Total Students: " + studentTotalCount);
        updateStudentPagination(studentTotalCount);
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify                     
    private javax.swing.JPanel Colleges;
    private javax.swing.JPanel Programs;
    private javax.swing.JPanel Students;
    private javax.swing.JButton btnAddCollege;
    private javax.swing.JButton btnAddProgram;
    private javax.swing.JButton btnAddStudent;
    private javax.swing.JButton btnClearCollege;
    private javax.swing.JButton btnClearProgram;
    private javax.swing.JButton btnClearStudent;
    private javax.swing.JButton btnDeleteCollege;
    private javax.swing.JButton btnDeleteProgram;
    private javax.swing.JButton btnDeleteStudent;
    private javax.swing.JButton btnSearchCollege;
    private javax.swing.JButton btnSearchProgram;
    private javax.swing.JButton btnSearchStudent;
    private javax.swing.JButton btnStudentNext;
    private javax.swing.JButton btnStudentPrev;
    private javax.swing.JButton btnUpdateCollege;
    private javax.swing.JButton btnUpdateProgram;
    private javax.swing.JButton btnUpdateStudent;
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JComboBox<String> cmbProgram;
    private javax.swing.JComboBox<String> cmbProgramCollege;
    private javax.swing.JComboBox<String> cmbStudentRows;
    private javax.swing.JComboBox<String> cmbYearLevel;
    private javax.swing.JLabel lblCollege;
    private javax.swing.JLabel lblCollegeCode;
    private javax.swing.JLabel lblCollegeCount;
    private javax.swing.JLabel lblCollegeName;
    private javax.swing.JLabel lblCollegeName2;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblProgram;
    private javax.swing.JLabel lblProgramCOde;
    private javax.swing.JLabel lblProgramCount;
    private javax.swing.JLabel lblRows;
    private javax.swing.JLabel lblStudentCount;
    private javax.swing.JLabel lblStudentID;
    private javax.swing.JLabel lblStudentPage;
    private javax.swing.JLabel lblYearLevel;
    private javax.swing.JPanel pnlCollegeButtons;
    private javax.swing.JPanel pnlCollegeInformation;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlProgramButtons;
    private javax.swing.JPanel pnlProgramInformation;
    private javax.swing.JPanel pnlStudentButtons;
    private javax.swing.JPanel pnlStudentInformation;
    private javax.swing.JPanel pnlStudentPagination;
    private javax.swing.JScrollPane scrColleges;
    private javax.swing.JScrollPane scrStudents;
    private javax.swing.JScrollPane srcProgam;
    private javax.swing.JTabbedPane tabMain;
    private javax.swing.JTable tblColleges;
    private javax.swing.JTable tblPrograms;
    private javax.swing.JTable tblStudents;
    private javax.swing.JTextField txtCollegeCode;
    private javax.swing.JTextField txtCollegeName;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtProgramCode;
    private javax.swing.JTextField txtProgramName;
    private javax.swing.JTextField txtStudentID;
    // End of variables declaration                   
}
